### ISSUE TITLE
android 获取返回值时挂了

### ISSUE THREAD

**Issue by txg17459** [pj0579/flutter_wechat#5]
错误如下：
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.hnzdsh.hnzdshapp.wxapi.WXEntryActivity" on path: DexPathList[[zip file "/data/app/com.hnzdsh.hnzdshapp-t71zngn40CGuqT5yg7N5Yw==/base.apk"],nativeLibraryDirectories=[/data/app/com.hnzdsh.hnzdshapp-t71zngn40CGuqT5yg7N5Yw==/lib/arm, /data/app/com.hnzdsh.hnzdshapp-t71zngn40CGuqT5yg7N5Yw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1190)

但我的工程里面有com.hnzdsh.hnzdshapp.wxapi.WXEntryActivity类

**Comment by pj0579** [comment]
在 AndroidManifest.xml里注册时 添加 android:exported="true"

**Comment by txg17459** [comment]
一直有这个，我就奇怪了，
